### ISSUE TITLE
Auto-ban

### ISSUE THREAD

**Issue by Zeinse** [HypestTeam/HypestBot#4]
For the bot to register who is banned, and prevent them by entering upon !seed or any action. 

!ban  would immediatly DQ and automatically sets a players challonge account (or IP) unable to join a Hypest Event. 

!ban from <date>to<date>  = Precise timed ban.
!unban

!clearbans<month> = Clear all bans for a precise month

**Comment by Rapptz** [comment]
The `!ban` command is possible except it would most likely have to be `!ban user days`. So.. `!ban rapptz 90` would ban me for 90 days.

Relevant challonge API link is [here](http://api.challonge.com/v1/documents/participants/destroy).
